name: action-checkout
on: [push]
jobs: 
    build-project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: 14
            - name: install-node_modules
              run: yarn
            - name: build-the-node
              run: yarn build
            - name: set-up-finish
              run: echo "setting up finished"
    
    run-project:
        needs: build-project
        runs-on: ubuntu-latest
        steps:
            run: echo "second project succeed"

